server:
  port: 8085
  servlet:
    session:
      tracking-modes: cookie

spring:
  messages.basename: lang.messages
  web.resources.static-locations: classpath:/spring-frontend/
  thymeleaf.prefix: classpath:/spring-frontend/
  security:
    user:
      name: admin
      password: admin
    oauth2:
      client:
        registration:
          facebook:
            client-id: 2205472349613842
            client-secret: 77d6778699ac224ab9daf0c963a11ebd
            scope:
              - email
              - public_profile

  datasource:
#    url: jdbc:p6spy:postgresql://localhost:5432/bookstore
    url: jdbc:postgresql://localhost:5432/bookstore
    username: ${DB_USER}
    password: ${DB_PASSWORD}
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: validate #create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

value:
  offset: 0
  limit: 20

upload:
  path: /home/shelby/Pictures/book-app-storage/book-covers
download:
  path: /home/shelby/Pictures/book-app-storage/book-files

auth:
  secret: skillbox
