server:
  port: 8085
  servlet:
    session:
      tracking-modes: cookie

spring:
  messages.basename: lang.messages
  web.resources.static-locations: classpath:/spring-frontend/
  thymeleaf.prefix: classpath:/spring-frontend/
  security:
    oauth2:
      client:
        registration:
          google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}

  datasource:
    #    url: jdbc:p6spy:postgresql://localhost:5432/bookstore
    url: jdbc:postgresql://localhost:5432/bookstore
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    hibernate.ddl-auto: validate #create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

value:
  offset: 0
  limit: 20

upload:
  path: /home/shelby/Pictures/book-app-storage/book-covers
download:
  path: /home/shelby/Pictures/book-app-storage/book-files

auth:
  secret: skillbox

lengthHash: 45